name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 14 * * 6'

permissions:
  contents: read
  security-events: write

jobs:
  mobsfscan:
    runs-on: ubuntu-latest
    name: MobSF Scan
    steps:
      - uses: actions/checkout@v6
      
      - name: Run mobsfscan
        uses: MobSF/mobsfscan@main
        with:
          args: . --sarif --output mobsf-results.sarif || true
      
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: mobsf-results.sarif
        if: always()

  scorecard:
    runs-on: ubuntu-latest
    name: Scorecard Analysis
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      
      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.4.3
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
      
      - name: Upload Scorecard SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: scorecard-results.sarif
